"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FeaturesList = exports.File = exports.TRANS_MODE = exports.SYNC_CLOSE_CODE = exports.SYNC_CODE = exports.LIST_IDS = exports.SPLIT_CHAR = exports.ENV_PARAMS = void 0;
exports.ENV_PARAMS = [
    'PORT',
    'BIND_IP',
    'ENABLE_DEBUG',
    'CONFIG_PATH',
    'LOG_PATH',
    'DATA_PATH',
    'PROXY_HEADER',
    'MAX_SNAPSHOT_NUM',
    'LIST_ADD_MUSIC_LOCATION_TYPE',
    'FRONTEND_PASSWORD',
    'WEBDAV_ENABLE',
    'WEBDAV_URL',
    'WEBDAV_USERNAME',
    'WEBDAV_PASSWORD',
    'WEBDAV_SYNC_PATH',
    'WEBDAV_BACKUP_PATH',
    'SYNC_INTERVAL',
    'BACKUP_INTERVAL',
    'WEBDAV_EXCLUDE_CACHE',
    'WEBDAV_EXCLUDE_MUSIC',
    'USER_ENABLE_PATH',
    'USER_ENABLE_ROOT',
    'ENABLE_WEBPLAYER_AUTH',
    'WEBPLAYER_PASSWORD',
    'DISABLE_TELEMETRY',
    'ENABLE_PUBLIC_USER_RESTRICTION',
    'ENABLE_PUBLIC_NON_ADMIN_LOCAL_MUSIC',
    'ENABLE_PUBLIC_NON_ADMIN_BROWSER_DOWNLOAD',
    'ENABLE_PUBLIC_NON_ADMIN_SERVER_CACHE',
    'ENABLE_PUBLIC_FAVORITES',
    'ENABLE_PUBLIC_NON_ADMIN_ACCESS',
    'ENABLE_CUSTOM_MUSIC_DIR',
    'ENABLE_LOGIN_USER_CACHE_RESTRICTION',
    'ENABLE_CACHE_SIZE_LIMIT',
    'CACHE_SIZE_LIMIT',
    'PROXY_ALL_ENABLED',
    'PROXY_ALL_ADDRESS',
    'ADMIN_PATH',
    'PLAYER_PATH',
    'SUBSONIC_ENABLE',
    'SUBSONIC_PATH',
    'SUBSONIC_PORT',
    'SUBSONIC_ENABLE_DEBUG',
    'SUBSONIC_ONLINE_SEARCH',
    'SUBSONIC_ONLINE_SEARCH_MODE',
    'SUBSONIC_ONLINE_SEARCH_SOURCES',
    'SUBSONIC_PUBLIC_LEADERBOARDS',
    'SUBSONIC_LEADERBOARD_SOURCE',
    'SUBSONIC_LYRIC_TRANSLATION',
    'SUBSONIC_CACHE_ON_PLAY',
    'SUBSONIC_PLAY_CACHE_FIRST',
    'SUBSONIC_QUALITY_ENABLED',
    'SUBSONIC_QUALITY_PRIORITY',
    'SUBSONIC_QUALITY_CLIENT_CAP_MODE',
    'SUBSONIC_SOURCE_PRIORITY',
    'SUBSONIC_SOURCE_CROSS_PLATFORM',
    'SUBSONIC_SOURCE_AUTOSWITCH_CUSTOM',
    'ARTIST_MAX_FETCH_PAGES',
    'CACHE_NAMING_PATTERN',
    'SYSTEM_ALLOW_UNSAFE_VM',
    'SINGER_SOURCE_PRIORITY',
    'CONFIG_BACKUP_ENABLE',
    'CONFIG_BACKUP_RETENTION_DAYS',
    'CONFIG_BACKUP_DIR',
    'SNAPSHOT_BACKUP_PATH',
    'SERVER_NAME',
    'LX_USER_',
];
exports.SPLIT_CHAR = {
    DISLIKE_NAME: '@',
    DISLIKE_NAME_ALIAS: '#',
};
exports.LIST_IDS = {
    DEFAULT: 'default',
    LOVE: 'love',
    TEMP: 'temp',
    DOWNLOAD: 'download',
    PLAY_LATER: null,
};
exports.SYNC_CODE = {
    helloMsg: 'Hello~::^-^::~v4~',
    idPrefix: 'OjppZDo6',
    authMsg: 'lx-music auth::',
    msgAuthFailed: 'Auth failed',
    msgBlockedIp: 'Blocked IP',
    msgConnect: 'lx-music connect',
    authFailed: 'Auth failed',
    missingAuthCode: 'Missing auth code',
    getServiceIdFailed: 'Get service id failed',
    connectServiceFailed: 'Connect service failed',
    connecting: 'Connecting...',
    unknownServiceAddress: 'Unknown service address',
};
exports.SYNC_CLOSE_CODE = {
    normal: 1000,
    failed: 4100,
};
exports.TRANS_MODE = {
    merge_local_remote: 'merge_remote_local',
    merge_remote_local: 'merge_local_remote',
    overwrite_local_remote: 'overwrite_remote_local',
    overwrite_remote_local: 'overwrite_local_remote',
    overwrite_local_remote_full: 'overwrite_remote_local_full',
    overwrite_remote_local_full: 'overwrite_local_remote_full',
    cancel: 'cancel',
};
exports.File = {
    serverInfoJSON: 'serverInfo.json',
    userDir: 'users',
    userDevicesJSON: 'devices.json',
    userSettingsJSON: 'settings.json',
    userSoundEffectsJSON: 'soundEffects.json',
    userTokensJSON: 'token.json',
    listDir: 'list',
    listSnapshotDir: 'snapshot',
    listSnapshotInfoJSON: 'snapshotInfo.json',
    dislikeDir: 'dislike',
    dislikeSnapshotDir: 'snapshot',
    dislikeSnapshotInfoJSON: 'snapshotInfo.json',
};
exports.FeaturesList = [
    'list',
    'dislike',
];
